# Generated by Django 3.2 on 2021-04-29 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Concert', 'verbose_name_plural': 'Concerts'},
        ),
        migrations.AlterModelOptions(
            name='concertliveset',
            options={'verbose_name': 'Concert Live Set', 'verbose_name_plural': 'Concert Live Sets'},
        ),
        migrations.AlterModelOptions(
            name='liveset',
            options={'verbose_name': 'Live Set', 'verbose_name_plural': 'Live Sets'},
        ),
        migrations.AlterModelOptions(
            name='nonprogrammableconfiguration',
            options={'verbose_name': 'Non Programmable Configuration', 'verbose_name_plural': 'Non Programmable Configurations'},
        ),
        migrations.AlterModelOptions(
            name='programmableconfiguration',
            options={'verbose_name': 'Programmable Configuration', 'verbose_name_plural': 'Programmable Configurations'},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
        migrations.AlterModelOptions(
            name='songset',
            options={'verbose_name': 'Song Set', 'verbose_name_plural': 'Songs Sets'},
        ),
        migrations.AlterField(
            model_name='song',
            name='non_programmable_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.nonprogrammableconfiguration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='programmable_configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.programmableconfiguration'),
        ),
    ]
