# Generated by Django 3.2 on 2021-04-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210429_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='non_programmable_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.nonprogrammableconfiguration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='programmable_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.programmableconfiguration'),
        ),
    ]
